# Generated by Django 5.2.4 on 2025-08-04 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the post', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Unique identifier for the post', max_length=200, unique=True, verbose_name='Slug')),
                ('content', models.TextField(help_text='Main content of the post', verbose_name='Content')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates if the post is published', verbose_name='Is Published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the post was published', verbose_name='Published At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the post was last updated', verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the post was created', verbose_name='Created At')),
                ('author', models.ForeignKey(help_text='Author of the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
