# Generated by Django 5.2.4 on 2025-08-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunnic', '0002_galleryimage_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Name of the comment author', max_length=500, verbose_name='Author')),
                ('content', models.TextField(help_text='Content of the comment', verbose_name='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the comment was created', verbose_name='Created At')),
                ('post', models.ForeignKey(help_text='Post to which the comment belongs', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kunnic.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
