# Generated by Django 5.2.4 on 2025-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunnic', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the gallery', upload_to='gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Caption for the image', max_length=255, null=True, verbose_name='Caption')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the image was uploaded', verbose_name='Upload Date')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-upload_date'],
            },
        ),
    ]
