# Generated by Django 5.2.4 on 2025-08-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunnic', '0003_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryImage',
        ),
    ]
